"""Initial schema

Revision ID: 1d563b0d9225
Revises: 
Create Date: 2026-07-24 16:18:43.352838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d563b0d9225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('request_snapshot_json', mysql.JSON(), nullable=True),
    sa.Column('result_snapshot_json', mysql.JSON(), nullable=True),
    sa.Column('metadata_json', mysql.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    op.create_table('evaluation_rule_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('evaluation_id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('result_status', sa.String(length=40), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('condition_results_json', mysql.JSON(), nullable=True),
    sa.Column('missing_fields_json', mysql.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_rule_results_evaluation_id'), 'evaluation_rule_results', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_rule_results_policy_id'), 'evaluation_rule_results', ['policy_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('request_json', mysql.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decision_confidence', sa.Integer(), nullable=False),
    sa.Column('winning_policy_id', sa.String(length=40), nullable=True),
    sa.Column('winning_policy_version', sa.Integer(), nullable=True),
    sa.Column('resolution_json', mysql.JSON(), nullable=True),
    sa.Column('explanation_json', mysql.JSON(), nullable=True),
    sa.Column('metrics_json', mysql.JSON(), nullable=True),
    sa.Column('warnings_json', mysql.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_correlation_id'), 'evaluations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_customer_id'), 'evaluations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_evaluations_decision'), 'evaluations', ['decision'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluated_at'), 'evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_evaluations_winning_policy_id'), 'evaluations', ['winning_policy_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('conditions_json', mysql.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('ai_metadata_json', mysql.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_policies_decision'), 'policies', ['decision'], unique=False)
    op.create_index(op.f('ix_policies_domain'), 'policies', ['domain'], unique=False)
    op.create_index('ix_policies_domain_status', 'policies', ['domain', 'status'], unique=False)
    op.create_index(op.f('ix_policies_priority'), 'policies', ['priority'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('status_snapshot', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('conditions_json', mysql.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ai_metadata_json', mysql.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_version')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_priority'), table_name='policies')
    op.drop_index('ix_policies_domain_status', table_name='policies')
    op.drop_index(op.f('ix_policies_domain'), table_name='policies')
    op.drop_index(op.f('ix_policies_decision'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_evaluations_winning_policy_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluated_at'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_decision'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_customer_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_correlation_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_evaluation_rule_results_policy_id'), table_name='evaluation_rule_results')
    op.drop_index(op.f('ix_evaluation_rule_results_evaluation_id'), table_name='evaluation_rule_results')
    op.drop_table('evaluation_rule_results')
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
