export const TELECOM_FIELDS = [
  { name: 'customer_id', label: 'Customer ID', type: 'string' },
  { name: 'customer_tenure_months', label: 'Customer Tenure', type: 'integer' },
  { name: 'credit_score', label: 'Credit Score', type: 'integer' },
  { name: 'payment_defaults', label: 'Payment Defaults', type: 'integer' },
  { name: 'fraud_risk_score', label: 'Fraud Risk Score', type: 'number' },
  { name: 'monthly_bill_amount', label: 'Monthly Bill Amount', type: 'number' },
  { name: 'requested_device_price', label: 'Requested Device Price', type: 'number' },
  { name: 'customer_segment', label: 'Customer Segment', type: 'string' },
  { name: 'current_plan', label: 'Current Plan', type: 'string' },
  { name: 'outstanding_balance', label: 'Outstanding Balance', type: 'number' },
  { name: 'is_existing_customer', label: 'Existing Customer', type: 'boolean' },
  { name: 'previous_upgrade_months_ago', label: 'Previous Upgrade (months ago)', type: 'integer' },
] as const

export const CUSTOMER_PRESETS = {
  eligible: {
    customer_id: 'CUST-1001',
    customer_tenure_months: 36,
    credit_score: 790,
    payment_defaults: 0,
    fraud_risk_score: 0.12,
    monthly_bill_amount: 3200,
    requested_device_price: 85000,
    customer_segment: 'PREMIUM' as const,
    current_plan: 'Magenta Max',
    outstanding_balance: 0,
    is_existing_customer: true,
    previous_upgrade_months_ago: 30,
  },
  highFraud: {
    customer_id: 'CUST-1002',
    customer_tenure_months: 42,
    credit_score: 785,
    payment_defaults: 0,
    fraud_risk_score: 0.91,
    monthly_bill_amount: 4000,
    requested_device_price: 95000,
    customer_segment: 'PREMIUM' as const,
    current_plan: 'Magenta Max',
    outstanding_balance: 0,
    is_existing_customer: true,
    previous_upgrade_months_ago: 28,
  },
  missingInfo: {
    customer_id: 'CUST-1003',
    customer_tenure_months: 18,
    customer_segment: 'STANDARD' as const,
  },
  outstandingBalance: {
    customer_id: 'CUST-1004',
    customer_tenure_months: 40,
    credit_score: 800,
    payment_defaults: 0,
    fraud_risk_score: 0.15,
    outstanding_balance: 18000,
    customer_segment: 'PREMIUM' as const,
  },
}
